import {Poppins} from "next/font/google";
import { ConnectingAirports } from '@mui/icons-material';
import { Logout } from '@mui/icons-material';
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link"
import "../globals.css";

export const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['300'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Itineraries",
  description: "Generated by create next app",
};

export default function Layout({children,}: {children: React.ReactNode;}) 
{
  return (
    <html lang="es">
      <body className={`${poppins.className}`}>
        <div className="flex min-h-screen "> 
          {/* Sidebar */} 
          <div className="w-64 p-4 border-r-2 border-solid border-gray-200 flex flex-col gap-8 items-center"> 
            <div>
              <Image
                src="/logos/auxo.svg"
                alt="Auxo logo"
                priority={true}
                width={400}
                height={400}
              />
            </div>
            <div className="h-4/5">
              <Link 
                href="/Itineraries" 
              className="w-48 h-12 flex items-center justify-center rounded-[8px] bg-[#DDF0F2] text-[#01C2D2] hover:bg-[#99f6e4] hover:text-gray-500"
              >
                <ConnectingAirports/>
                Itineraries
              </Link>
            </div>
            {/*sidebar foot */}
            <div >
              <Link 
                  href="/Itineraries" 
                className="w-48 h-12 flex items-center justify-center pt-4 border-t border-[#01C2D2] text-center text-gray-500 hover:text-[#01C2D2]"
                >
                <Logout/>
                logout
              </Link>              
            </div>
            
          </div> 

          {/*Content*/}
          {children}
        </div>
      </body>
    </html>
  );
}
